[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "genpnize"
description = "Format text like the Producer"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "nikkie", email = "takuyafjp+develop@gmail.com" }]
keywords = ["text", "format"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/ftnext/genpnize"

[project.scripts]
genpnize = "genpnize:main"

[tool.maturin]
bindings = "pyo3"
manifest-path = "bindings-py/Cargo.toml"
